### PR TITLE
[FIX] search param in url

### PR DESCRIPTION
**Pull request by a-k-s-h-a-y**
**Url** : localhost:8069/test/?param1=value&param2=value
 
### On clicking debug

**Expected Behavior**  : localhost:8069/test/?param1=value&param2=value&debug=assets

**Current Behavior**  : localhost:8069/test/?debug=assets

### CODE REVIEW

**Comment by akshaynesm** [comment]
@jat-odoo

**Comment by JKE-be** [comment]
Thanks

This repository is not owned by Odoo but Droggol ;)

But thanks for your contributions in all cases.

**Comment by akshaynesm** [comment]
oh I knew that, I've seen the Droggol website :)
Its just that I've been facing this issue for a while now and thought I'd give it a try.

**Comment by andrp92** [comment]
This is a good suggestion. I've been having this issue myself for a while now.

**Comment by jat-odoo** [comment]
@a-k-s-h-a-y Thank you for your contribution. :+1:

Can you squash commits into single with more meaningful commit message?
Also, please update extension version to `4.1`.

Sorry for the late reply. :stuck_out_tongue_winking_eye:

**Comment by jat-odoo** [comment]
Thanks @a-k-s-h-a-y

**Pull request merged**
